* Instructions for H4G MicroAOD production
** Setup
   Before you start, **please take note** of these warnings and comments:
   - **N.B.** The setup script will check out many packages and take a while!
   - **N.B.** You can ignore "error: addinfo_cache" lines.
   - **N.B.** These setup instructions now include the STXS workflow

   Supported releases:
   - 10_6_1_patch2 required for the STXS stage 1.1 information
   - 10_6_8 required for the STXS stage 1.2 information

   get flashgg:
   #+BEGIN_EXAMPLE
   export SCRAM_ARCH=slc7_amd64_gcc700
   cmsrel CMSSW_10_6_8
   cd CMSSW_10_6_8/src
   cmsenv
   git cms-init
   cd $CMSSW_BASE/src
   git clone -b h4g_microAOD_prod  git@github.com:wamorkart/flashgg.git
   source flashgg/setup_flashgg.sh
   #+END_EXAMPLE

   If everything now looks reasonable, you can build:
   #+BEGIN_EXAMPLE
   cd $CMSSW_BASE/src
   scram b -j 4
   #+END_EXAMPLE

** Things to do
    You should copy the xml weight files that are required for microAOD production to an area before CRAB job submission. This is to ensure that the tar ball of the CRAB job is not big (the jobs crash if it is larger than 200 MB).
    #+BEGIN_EXAMPLE
    cd CMSSW_10_6_8/src/flashgg
    mkdir ../../external/slc7_amd64_gcc700/data/
    #+END_EXAMPLE

    I found that copying just the following weights file was enough to successfully run the microAOD production:
    #+BEGIN_EXAMPLE
    cp MicroAOD/data/HggPhoId_94X_barrel_BDT_v2.weights.xml ../../external/slc7_amd64_gcc700/data/
    cp MicroAOD/data/HggPhoId_94X_endcap_BDT_v2.weights.xml ../../external/slc7_amd64_gcc700/data/
    cp MicroAOD/data/TMVAClassification_BDTVtxId_SL_2016.xml ../../external/slc7_amd64_gcc700/data/
    cp MicroAOD/data/TMVAClassification_BDTVtxProb_SL_2016.xml ../../external/slc7_amd64_gcc700/data/
    #+END_EXAMPLE

    Also, make the following changes in the metaconditions json files (MetaData/data/MetaConditions/Era2016_RR-17Jul2018_v1.json, MetaData/data/MetaConditions/Era2017_RR-31Mar2018_v1.json  and MetaData/data/MetaConditions/Era2018_RR-17Sep2018_v1.json):
    #+BEGIN_EXAMPLE
    "photonIdMVAweightfile_EB" : "flashgg/MicroAOD/data/HggPhoId_94X_barrel_BDT_v2.weights.xml", -> "photonIdMVAweightfile_EB" : "HggPhoId_94X_barrel_BDT_v2.weights.xml",
    "photonIdMVAweightfile_EE" : "flashgg/MicroAOD/data/HggPhoId_94X_endcap_BDT_v2.weights.xml", -> "photonIdMVAweightfile_EE" : "HggPhoId_94X_endcap_BDT_v2.weights.xml",
    "vertexIdMVAweightfile" : "flashgg/MicroAOD/data/TMVAClassification_BDTVtxId_SL_2016.xml", -> "vertexIdMVAweightfile" : "TMVAClassification_BDTVtxId_SL_2016.xml",
    "vertexProbMVAweightfile" : "flashgg/MicroAOD/data/TMVAClassification_BDTVtxProb_SL_2016.xml" -> "vertexProbMVAweightfile" : "TMVAClassification_BDTVtxProb_SL_2016.xml"         
    #+END_EXAMPLE
